# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-25 18:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(default=b'')),
                ('api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('steam_username', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
