# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-01 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20151227_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='debug_mode',
            field=models.BooleanField(default=True),
        ),
    ]
